### ISSUE TITLE
Discord Link Expired

### ISSUE THREAD

**Issue by Kulcanhez** [vectrejs/vectre#6]
Hello team!

Congratulations for the v1 release. I'm really curious to try it out and hope more people come as it seems really fast and easy to use.

Meanwhile, I noticed the link for the discord has expired.

Really thank you for this project!

**Comment by vatson** [comment]
Greetings @Kulcanhez 

Thanks for the kind words!

The discord link was updated in documentation and README as well. The changes were published.
